#!/usr/bin/env bash
# Regenerates .clangd so the editor can resolve AVR headers.
#
# clangd runs a host-targeted clang, so without help it (a) can't find avr-libc
# headers and (b) takes the non-AVR branch of every library's #ifdef ladder.
# We therefore inject the avr-gcc include dirs and the arch macros that
# -mmcu=atmega32u4 would normally imply.
set -euo pipefail
BUILD_DIR="${1:-.build}"

PGM=$(find "$HOME/Library/Arduino15/packages/arduino/tools/avr-gcc" \
        -type f -path '*/avr/include/avr/pgmspace.h' 2>/dev/null \
      | awk '{print length, $0}' | sort -n | head -1 | cut -d' ' -f2-)
[ -n "$PGM" ] || { echo "avr-gcc headers not found; run 'arduino-cli compile' first" >&2; exit 1; }
AVRINC=${PGM%/avr/pgmspace.h}
GCCINC=$(find "$HOME/Library/Arduino15/packages/arduino/tools/avr-gcc" \
           -type d -path '*/lib/gcc/avr/*/include' 2>/dev/null | sort | head -1)

cat > .clangd <<EOF
# GENERATED by tools/gen-clangd.sh - do not edit; run 'make db' instead.
CompileFlags:
  CompilationDatabase: ${BUILD_DIR}
  Compiler: avr-g++
  Add:
    - -isystem${AVRINC}
    - -isystem${GCCINC}
    - -D__AVR__
    - -D__AVR_ATmega32U4__
    - -D__AVR_ARCH__=5
    - -DUSBCON
    - -Wno-unknown-warning-option
  Remove:
    - -mmcu=*
    - -flto*
    - -fno-fat-lto-objects
Diagnostics:
  Suppress: [pp_file_not_found_angled_include_not_fatal]
EOF
echo "Wrote .clangd (avr-libc: $AVRINC)"
